baseURL = "https://tyron.alwaysdata.net/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Wepfen"

theme = "gokarna"

enableRobotsTXT = false
enableEmoji = true

# https://gohugo.io/content-management/syntax-highlighting/
pygmentsStyle = "monokai"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2
	
  [[menu.main]]
    identifier = "cramptes"
    name = "Cramptés"
    url = "/cramptes/"
    weight = 4
	
  [[menu.main]]
    identifier = "whoami"
    name = "Whoami"
    url = "/whoami/"
    weight = 5

	
[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-xl"

  # Description to display on homepage
  description = "Cybersecurity student | Noob-Tier CTF player"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#445D48"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  #customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo", "writeups", "infosec", "2600", "cybersecurity", "CTF"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  #showPostsOnHomePage = ""
  
  togglePreviousAndNextButtons = "true"
  # Footer text
  footer = ""
  
  socialIcons = [
    {name = "github", url = "https://github.com/1Tyron140"}
  ]
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false